package frc.robot.subsystems.swerve;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;

import choreo.Choreo.TrajectoryLogger;
import choreo.auto.AutoFactory;
import choreo.auto.AutoTrajectory;
import choreo.trajectory.SwerveSample;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.filter.SlewRateLimiter;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.RobotContainer;
import frc.robot.subsystems.shooter.autoaim.SOTMCalcs;
import frc.robot.subsystems.swerve.generated.TunerConstants;
import frc.robot.subsystems.swerve.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.vision.Localization;
import frc.robot.subsystems.vision.Localization.RRPoseEstimate;

import redrocklib.logging.SmartDashboardBoolean;
import redrocklib.logging.SmartDashboardNumber;
// import redrocklib.wrappers.RedRockCamera;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static CommandSwerveDrivetrain instance = null;

    private Alliance alliance = Alliance.Blue;

    private boolean ignoreCameraPoseDistance = true;

    private CommandXboxController controller;

    private boolean driveLimiterEnabled = false;

    private boolean inLobZone = false;

    private SlewRateLimiter driveSlewRateLimiterX = new SlewRateLimiter(3);
    private SlewRateLimiter driveSlewRateLimiterY = new SlewRateLimiter(3);
    private SlewRateLimiter rotateSlewRateLimiter = new SlewRateLimiter(3);

    private SmartDashboardNumber limitedMaxDriveSpeed = new SmartDashboardNumber("dt/dt sotm/drive speeds", 2);
    private SmartDashboardNumber limitedMaxRotateSpeed = new SmartDashboardNumber("dt/dt sotm/rotate speeds", 0.5);

    private SmartDashboardNumber lobLimitDriveSpeed = new SmartDashboardNumber("dt/dt lob speeds/drive speed", 2.75);
    private SmartDashboardNumber lobLimitTurnSpeed = new SmartDashboardNumber("dt/dt lob speeds/turn speed", 0.75);

    private SmartDashboardNumber poseMaxDistance = new SmartDashboardNumber("dt/dt localization/dist restriction", 6);
    private SmartDashboardNumber poseMaxRotation = new SmartDashboardNumber("dt/dt localization/rotation restriction", 10);

    private SmartDashboardNumber maxDriveSpeed = new SmartDashboardNumber("dt/dt drive speeds/max drive mps", 6);
    private SmartDashboardNumber maxTurnSpeed = new SmartDashboardNumber("dt/dt drive speeds/turn rotps", 1.6);
    private SmartDashboardNumber drivingDeadBand = new SmartDashboardNumber("dt/dt thresholds/deadband", 0.005);
    private SmartDashboardNumber pidRotationThreshold = new SmartDashboardNumber("dt/dt thresholds/rotation threshold", 1); // threshold to enable heading pid again.

    private SmartDashboardNumber headingP = new SmartDashboardNumber("dt/dt heading pid coeffs/kP", 4, false);
    private SmartDashboardNumber headingI = new SmartDashboardNumber("dt/dt heading pid coeffs/kI", 0, false);
    private SmartDashboardNumber headingD = new SmartDashboardNumber("dt/dt heading pid coeffs/kD", 0, false);

    private SmartDashboardNumber poseP = new SmartDashboardNumber("dt/dt pose coeffs/kP", 0);
    private SmartDashboardNumber poseI = new SmartDashboardNumber("dt/dt pose coeffs/kI", 0);
    private SmartDashboardNumber poseD = new SmartDashboardNumber("dt/dt pose coeffs/kD", 0);

    private SmartDashboardNumber pidToPoseMaxVelo = new SmartDashboardNumber("dt/dt pose coeffs/max velo", 3);

    private PIDController poseXController;
    private PIDController poseYController;

    private SmartDashboardNumber headingTolerance = new SmartDashboardNumber("dt/dt heading pid coeffs/tolerance", 0.015);
    
    private final SwerveRequest.FieldCentric drive = new SwerveRequest.FieldCentric()
            .withDeadband(maxDriveSpeed.getNumber() * drivingDeadBand.getNumber()).withRotationalDeadband(maxTurnSpeed.getNumber() * drivingDeadBand.getNumber()) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage); // Use open-loop control for drive motors

    private final SwerveRequest.FieldCentricFacingAngle driveFacingAngle = new SwerveRequest.FieldCentricFacingAngle()
            .withDeadband(maxDriveSpeed.getNumber() * drivingDeadBand.getNumber()).withRotationalDeadband(maxTurnSpeed.getNumber() * drivingDeadBand.getNumber()) // Add a 10% deadband
            .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    private Telemetry telemetry = new Telemetry(maxDriveSpeed.getNumber());

    private Rotation2d targetAngle = new Rotation2d();
    private Pose2d targetPose = new Pose2d();

    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    // private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    // private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during field-centric path following */
    private final SwerveRequest.ApplyFieldSpeeds m_pathApplyFieldSpeeds = new SwerveRequest.ApplyFieldSpeeds();
    private final PIDController m_pathXController = new PIDController(10, 0, 0);
    private final PIDController m_pathYController = new PIDController(10, 0, 0);
    private final PIDController m_pathThetaController = new PIDController(7, 0, 0);

    private AutoFactory factory;


    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        initialize();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        initialize();
    }

    private void initialize() {
        this.configureHeadingPID();
        this.registerTelemetry(telemetry::telemeterize);
        this.register();
        this.factory = this.createAutoFactory();

        this.poseXController = new PIDController(poseP.getNumber(), poseI.getNumber(), poseD.getNumber());
        this.poseYController = new PIDController(poseP.getNumber(), poseI.getNumber(), poseD.getNumber());
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        this.initialize();
    }

    /**
     * Creates a new auto factory for this drivetrain.
     *
     * @return AutoFactory for this drivetrain
     */
    public AutoFactory createAutoFactory() {
        return createAutoFactory((sample, isStart) -> {});
    }

    /**
     * Creates a new auto factory for this drivetrain with the given
     * trajectory logger.
     *
     * @param trajLogger Logger for the trajectory
     * @return AutoFactory for this drivetrain
     */
    public AutoFactory createAutoFactory(TrajectoryLogger<SwerveSample> trajLogger) {
        return new AutoFactory(
            () -> getState().Pose,
            this::resetPose,
            this::followPath,
            true,
            this,
            trajLogger
        );
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Follows the given field-centric path sample with PID.
     *
     * @param sample Sample along the path to follow
     */
    public void followPath(SwerveSample sample) {
        m_pathThetaController.enableContinuousInput(-Math.PI, Math.PI);

        var pose = getState().Pose;

        var targetSpeeds = sample.getChassisSpeeds();
        targetSpeeds.vxMetersPerSecond += m_pathXController.calculate(
            pose.getX(), sample.x
        );
        targetSpeeds.vyMetersPerSecond += m_pathYController.calculate(
            pose.getY(), sample.y
        );
        targetSpeeds.omegaRadiansPerSecond += m_pathThetaController.calculate(
            pose.getRotation().getRadians(), sample.heading
        );

        setControl(
            m_pathApplyFieldSpeeds.withSpeeds(targetSpeeds)
                .withWheelForceFeedforwardsX(sample.moduleForcesX())
                .withWheelForceFeedforwardsY(sample.moduleForcesY())
        );
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */

        // if (DriverStation.isAutonomous()) return;

        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            // DriverStation.getAlliance().ifPresent(allianceColor -> {
            //     setOperatorPerspectiveForward(
            //         allianceColor == Alliance.Red
            //             ? kRedAlliancePerspectiveRotation
            //             : kBlueAlliancePerspectiveRotation
            //     );
                m_hasAppliedOperatorPerspective = true;
                if (DriverStation.getAlliance().isPresent() && DriverStation.getAlliance().get() == Alliance.Red) {
                    this.alliance = Alliance.Red;
                    this.fieldCentricSeedOffset = Rotation2d.k180deg;
                } else {
                    this.alliance = Alliance.Blue;
                    this.fieldCentricSeedOffset = Rotation2d.kZero;
                }
        }

        poseXController.setPID(poseP.getNumber(), poseI.getNumber(), poseD.getNumber());
        poseYController.setPID(poseP.getNumber(), poseI.getNumber(), poseD.getNumber());

        telemetry.setMaxSpeed(maxDriveSpeed.getNumber());

        this.updateDeadbands();
        this.updateHeadingPIDValues();

        if (this.state != DriveState.AUTO) {
            this.updateDriveState();
            this.setControl(this.getRequest());
        } else if (this.state == DriveState.AUTO) {
            this.setTargetHeading(this.getPose().getRotation());
        }
        SmartDashboard.putString("dt/drive state", this.state.toString());
        SmartDashboard.putNumber("dt/field centric offset", this.fieldCentricSeedOffset.getDegrees());
        SmartDashboard.putString("alliance", this.alliance.toString());
        SmartDashboard.putBoolean("dt/ignore camera pose distance", ignoreCameraPoseDistance);

        if (this.visionEnabled.getValue() && !DriverStation.isDisabled()) updateVisionMeasurements();
    }

    private void updateVisionMeasurements() {
        if (this.getRotationRate() >= poseMaxRotation.getNumber()) {
            return;
        }
        for (RRPoseEstimate estimate : Localization.getPoseEstimates()) {
            if (estimate.pose.equals(new Pose2d())) continue;
            if (!ignoreCameraPoseDistance && estimate.pose.getTranslation().getDistance(this.getPose().getTranslation()) > poseMaxDistance.getNumber() 
                && !DriverStation.isDisabled()) 
                continue;
            this.addVisionMeasurement(estimate.pose, estimate.timeStamp, estimate.stdvs);
        }
    }

    private void updateDeadbands() {
        drive.withDeadband(drivingDeadBand.getNumber() * maxDriveSpeed.getNumber()).withRotationalDeadband(drivingDeadBand.getNumber() * maxTurnSpeed.getNumber());
        driveFacingAngle.withDeadband(drivingDeadBand.getNumber() * maxDriveSpeed.getNumber()).withRotationalDeadband(drivingDeadBand.getNumber() * maxTurnSpeed.getNumber());
    }

    private void updateHeadingPIDValues() {
        this.driveFacingAngle.HeadingController.setPID(headingP.getNumber(), headingI.getNumber(), headingD.getNumber());
        this.driveFacingAngle.HeadingController.setTolerance(headingTolerance.getNumber());
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public enum DriveState {
        DRIVE,
        DRIVE_RESIDUAL,
        DRIVE_FACING_ANGLE,
        AUTO,
        PID_TO_POSE
    }

    private DriveState state = DriveState.DRIVE_FACING_ANGLE;

    private Rotation2d fieldCentricSeedOffset = new Rotation2d();

    private SmartDashboardBoolean visionEnabled = new SmartDashboardBoolean("vision enabled", true);

    public void enablePoseTargeting(Pose2d targetPose) {
        this.targetPose = targetPose;
        this.setTargetHeading(targetPose.getRotation());
        this.setDriveState(DriveState.PID_TO_POSE);
    }

    public void setDriveState(DriveState state) {
        this.state = state;
    }

    public DriveState getDriveState() {
        return this.state;
    }

    public Pose2d getPose() {
        return this.getState().Pose;
    }

    public void enableIgnoreCameraDistance() {
        this.ignoreCameraPoseDistance = true;
    }

    public void disableIgnoreCameraDistance() {
        // this.ignoreCameraPoseDistance = false;
        this.ignoreCameraPoseDistance = true;
    }

    public void enableVision() {
        this.visionEnabled.putBoolean(true);
    }

    public void disableVision() {
        this.visionEnabled.putBoolean(false);
    }

    public void setInLobZone(boolean b) {
        this.inLobZone = b;
    }

    public void toggleVision() {
        if (this.visionEnabled.getValue()) this.visionEnabled.putBoolean(false);
        else this.visionEnabled.putBoolean(true);
    }

    public Command toggleVisionCommand() {
        return Commands.runOnce(() -> this.toggleVision());
    }

    public void enableSpeedLimiter() {
        this.driveLimiterEnabled = true;
    }

    public void disableSpeedLimiter() {
        this.driveLimiterEnabled = false;
    }

    private void configureHeadingPID() {
        driveFacingAngle.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
        this.updateHeadingPIDValues();
    }

    public SwerveRequest getRequest() {
        double rawX = -controller.getLeftY();
        double rawY = -controller.getLeftX();
        double rawRotation = -controller.getRightX();

        double slewX = driveSlewRateLimiterX.calculate(rawX);
        double slewY = driveSlewRateLimiterY.calculate(rawY);
        double slewRot = rotateSlewRateLimiter.calculate(rawRotation);

        double limitDrive = limitedMaxDriveSpeed.getNumber();
        double limitTurn = limitedMaxRotateSpeed.getNumber();

        if (inLobZone) {
            limitDrive = lobLimitDriveSpeed.getNumber();
            limitTurn = lobLimitTurnSpeed.getNumber();
        }

        double slewRequestedX = slewX * limitDrive;
        double slewRequestedY = slewY * limitDrive;
        double slewRequestedRot = slewRot * RotationsPerSecond.of(limitTurn).in(RadiansPerSecond);

        double requestedXSpeed = -controller.getLeftY() * maxDriveSpeed.getNumber();
        double requestedYSpeed = -controller.getLeftX() * maxDriveSpeed.getNumber();
        double requestedRotationSpeed = -controller.getRightX() * RotationsPerSecond.of(maxTurnSpeed.getNumber()).in(RadiansPerSecond);

        double pidToPoseMax = pidToPoseMaxVelo.getNumber(); 

        if (driveLimiterEnabled || Math.abs(controller.getRightTriggerAxis()) > RobotContainer.kTriggerThreshold) {
            if (Math.abs(rawX) < drivingDeadBand.getNumber()) {
                requestedXSpeed = 0;
                driveSlewRateLimiterX.reset(0);
            } else {
                requestedXSpeed = slewRequestedX;
            }
            if (Math.abs(rawY) < drivingDeadBand.getNumber()) {
                requestedYSpeed = 0;
                driveSlewRateLimiterY.reset(0);
            } else {
                requestedYSpeed = slewRequestedY;
            }
            if (Math.abs(rawRotation) < drivingDeadBand.getNumber()) {
                requestedRotationSpeed = 0;
                rotateSlewRateLimiter.reset(0);
            } else {
                requestedRotationSpeed = slewRequestedRot;
            }
        }
        
        SmartDashboard.putNumber("dt/raw x", rawX);
        SmartDashboard.putNumber("dt/requested x", requestedXSpeed);

        SmartDashboard.putBoolean("dt/in lob zone", inLobZone);

        double[] rotatedRequestedSpeed = SOTMCalcs.rotate(requestedXSpeed, requestedYSpeed, fieldCentricSeedOffset);

        requestedXSpeed = rotatedRequestedSpeed[0];
        requestedYSpeed = rotatedRequestedSpeed[1];



        Pose2d dtPose = this.getPose();
        switch (state) {
            case DRIVE_RESIDUAL:
                return drive.withVelocityX(requestedXSpeed).withVelocityY(requestedYSpeed).withRotationalRate(0);
            case DRIVE_FACING_ANGLE:
                return driveFacingAngle.withVelocityX(requestedXSpeed).withVelocityY(requestedYSpeed).withTargetDirection(this.targetAngle);
            case DRIVE:
                return drive.withVelocityX(requestedXSpeed).withVelocityY(requestedYSpeed).withRotationalRate(requestedRotationSpeed);
            case PID_TO_POSE:
                return driveFacingAngle
                    .withVelocityX(MathUtil.clamp(poseXController.calculate(dtPose.getX(), targetPose.getX()), -pidToPoseMax, pidToPoseMax))
                    .withVelocityY(MathUtil.clamp(poseYController.calculate(dtPose.getY(), targetPose.getY()), -pidToPoseMax, pidToPoseMax))
                    .withTargetDirection(targetPose.getRotation());
            default:
                return new SwerveRequest.Idle();
        }
    }

    public void updateDriveState() {
        switch (state) {
            case AUTO: break;
            case PID_TO_POSE: break;
            case DRIVE_FACING_ANGLE:
                if (Math.abs(controller.getRightX()) >= drivingDeadBand.getNumber()) state = DriveState.DRIVE;
                break;
            case DRIVE:
                if (Math.abs(controller.getRightX()) <= drivingDeadBand.getNumber()) state = DriveState.DRIVE_RESIDUAL;
                break;
            case DRIVE_RESIDUAL:
                if (Math.abs(controller.getRightX()) >= drivingDeadBand.getNumber()) state = DriveState.DRIVE;
                else {
                    SwerveDriveState driveState = this.getState();
                    if (Math.abs(driveState.Speeds.omegaRadiansPerSecond) <= 
                        DegreesPerSecond.of(pidRotationThreshold.getNumber()).in(RadiansPerSecond)) {
                        targetAngle = driveState.Pose.getRotation();
                        state = DriveState.DRIVE_FACING_ANGLE;
                    }
                }
                break;
        }
    }
    public void seedHeading() {
        this.fieldCentricSeedOffset = this.getState().Pose.getRotation();
        this.targetAngle = this.fieldCentricSeedOffset;
    }

    public double getRotationRate() {
        return this.getState().Speeds.omegaRadiansPerSecond;
    }

    public Command resetHeadingCommand() {
        return this.runOnce(this::seedHeading);
    }

    public CommandSwerveDrivetrain withController(CommandXboxController controller) {
        this.controller = controller;
        return this;
    }

    public void setTargetHeading(Rotation2d target) {
        this.targetAngle = target;
    }

    public void setTargetHeadingToCurrentHeading() {
        this.targetAngle = this.getPose().getRotation();
    }

    public Command setTargetHeadingCommand(Rotation2d target) {
        return this.runOnce(() -> this.targetAngle = target);
    }

    public Command setTargetHeadingToCurrentHeadingCommand() {
        return this.runOnce(() -> this.setTargetHeadingToCurrentHeading());
    }

    public boolean isBlue() {
        return this.alliance == Alliance.Blue;
    }

    public void resetKalaman(Pose2d pose) {
        this.resetPose(pose);
    }

    @Override
    public void resetPose(Pose2d pose) {
        super.resetPose(pose);
        this.setTargetHeading(pose.getRotation());
    }

    public Command followTrajectory(String pathName) {
        return Commands.sequence(
            this.runOnce(() -> this.setDriveState(DriveState.AUTO)),
            this.factory.trajectoryCmd(pathName),
            this.setTargetHeadingToCurrentHeadingCommand(),
            this.runOnce(() -> this.setDriveState(DriveState.DRIVE_FACING_ANGLE))
        );
    }

    public Command followTrajectoryMirrored(String pathName) {
        return Commands.sequence(
            this.runOnce(() -> this.setDriveState(DriveState.AUTO)),
            this.factory.trajectoryCmd(pathName, AutoTrajectory::mirrorY),
            this.setTargetHeadingToCurrentHeadingCommand(),
            this.runOnce(() -> this.setDriveState(DriveState.DRIVE_FACING_ANGLE))
        );
    }

    public Command followTrajectory(String pathName, int index) {
        return Commands.sequence(
            this.runOnce(() -> this.setDriveState(DriveState.AUTO)),
            this.factory.trajectoryCmd(pathName, index),
            this.setTargetHeadingToCurrentHeadingCommand(),
            this.runOnce(() -> this.setDriveState(DriveState.DRIVE_FACING_ANGLE))
        );
    }

    public Command pidToPoseAutoCommand(Pose2d targetPose) {
        return Commands.sequence(
            Commands.runOnce(() -> this.enablePoseTargeting(targetPose)),
            Commands.waitUntil(() -> poseXController.atSetpoint() && poseYController.atSetpoint()),
            Commands.runOnce(() -> this.setDriveState(DriveState.AUTO))
        );
    }

    public Command resetOdometryCommand(String pathName) {
        return this.factory.resetOdometry(pathName);
    }

    public Command resetOdometryCommand(String pathName, int index) {
        return this.factory.resetOdometry(pathName, index);
    }

    public void setLowerCurrentLimits() {
        // var modules = this.getModules();
        // for (int i = 0; i < modules.length; i++) {
        //     this.getModule(i).getDriveMotor().getConfigurator().apply(
        //         new CurrentLimitsConfigs()
        //         .withSupplyCurrentLimit(45)
        //         .withSupplyCurrentLimitEnable(true)
        //         .withStatorCurrentLimit(80)
        //         .withStatorCurrentLimitEnable(true)
        //     );
        // }
    }

    public static CommandSwerveDrivetrain getInstance() {
        if (instance == null) instance = TunerConstants.createDrivetrain();
        return instance;
    }
}
